region: ap-northeast-1
cluster: example-prod-foobar
service: example-prod-foobar
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: "10m0s"
plugins:
  - name: tfstate
    config:
      url: s3://terraform-backend-353981446712/LaravelApp_Dev_Book_MyCodes_tfstateFile/prod/cicd/app_foobar_v1.0.0.tfstate
